#!/usr/bin/python3

def raise_exception():
    print("{}".format(1 + '2'))
